FROM debian:bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
	php-fpm \
	php-mysql \
	curl \
	sendmail \
	ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i 's|^listen = .*|listen = 9000|' /etc/php/*/fpm/pool.d/www.conf \
    && mkdir -p /run/php

RUN curl -fsSL https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o /usr/local/bin/wp \
    && chmod +x /usr/local/bin/wp

# Disable PHP mail() for both CLI and FPM so nothing blocks
RUN set -eux; \
  for d in /etc/php/*/fpm/conf.d /etc/php/*/cli/conf.d; do \
    mkdir -p "$d"; \
    printf "sendmail_path = /bin/true\n" > "$d/99-disable-mail.ini"; \
  done

WORKDIR /var/www/html

COPY ./tools/wordpress.sh /usr/local/bin/wordpress.sh
RUN chmod +x /usr/local/bin/wordpress.sh

ENTRYPOINT ["/usr/local/bin/wordpress.sh"]